name: 'Release Universal macOS Build'

on:
  push:
    tags:
      - 'v*-universal' # Special tags for universal builds
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release (universal)'
        required: true
        default: 'v0.1.0-universal'

jobs:
  build-universal-macos:
    permissions:
      contents: write
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin,x86_64-apple-darwin

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './packages/game/src-tauri -> target'

      - name: Install dependencies
        run: |
          bun install --frozen-lockfile || bun install
          cd packages/game
          bun install --frozen-lockfile || bun install

      - name: Build frontend
        run: |
          cd packages/game
          bun run build:frontend || bun run build

      - name: Build universal binary
        run: |
          cd packages/game
          bun run tauri:build:universal || bunx tauri build --target universal-apple-darwin

      - name: Get version
        run: echo "PACKAGE_VERSION=$(node -pe "require('./packages/game/package.json').version")" >> $GITHUB_ENV

      - name: Create Release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        with:
          tagName: v${{ env.PACKAGE_VERSION }}-universal
          releaseName: ElizaOS Game v${{ env.PACKAGE_VERSION }} Universal
          releaseBody: |
            Universal macOS build for both Intel and Apple Silicon Macs.

            This build contains both x86_64 and aarch64 architectures in a single binary.
          releaseDraft: false
          prerelease: false
          projectPath: packages/game
          args: --target universal-apple-darwin
          tauriScript: bunx tauri
          includeDebug: false
          includeRelease: true
